* Overview
A learning exercise for working with networks and optimizing code to perform well for large N networks. This files in the =old/= library so far performs decently for my simplistic use cases for N ~ 1e5 as an upper limit.

I think it might be worth converting the entire library to use sparse matrices instead of dictionary based adjacency lists given that sparse networks are far more common. The performance will not improve per se by doing this, but the memory impact is considerable.

* List of Features
- AbstractGraph containing =Graph=, =WeightedGraph=
- Basic methods for manipulating and getting details of both
  - nodes: Returns a Set of nodes in the network
  - neighbor: Returns the neighbors of a node as a vector
  - degrees: Returns a dictionary of the form {node : degree}
  - degree_average: Average degree of the network
  - degree_distribution: returns a pair of vectors specifying degrees, and frequencies respectively
  - add, delete link(s): self-explanatory
  - edges: Return an edge-list
  - ne: Count of edges
  - copy: Create a copy of a graph that can be operated independently
  - nv: number of nodes of a graph
  - largest_node: node with largest label (useful for integer index networks where you wish to loop over N)
- Some Graph specific methods:
  - Graphs: adjacency_to_graph converts a vector of adjacencies to a =Graph= object
  - WeightedGraph: weights_to_weightedGraph, weightedGraph_to_weights convert between a matrix of weights and a =WeightedGraph= object
- Distances & Measures
  - Dijkstra's
  - Betweenness Centrality
  - Incremental Betweenness Updates for single edge insertion/weight decrease ([[https:https://arxiv.org/abs/1704.08592][iBet paper E. Bergamini et.al.]])
- Dictionary based approach for constant time insert and read
- Modified Implementation of Dijkstras' algorithm inspired from =Graph.jl= to work with my Dict
- Connected components detection also appropriated from =Graph.jl=
- Unsurprisingly, the vector implementation is faster and is thus the default.

* Future optimizations
- For Simple graphs, make graph struct a Vector of Sets
- Adapt Struct to allow arbitrary node labels
